# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='starland_chat_agent',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\x12\x13starland_chat_agent\"b\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63haracter_id\x18\x02 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x03 \x01(\t\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\"D\n\x0c\x43hatResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t\x12\x15\n\rresponse_text\x18\x03 \x01(\t\"B\n\x12\x43hatStreamResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t\x12\r\n\x05\x63hunk\x18\x03 \x01(\t2\xb3\x01\n\x05\x41gent\x12M\n\x04\x43hat\x12 .starland_chat_agent.ChatRequest\x1a!.starland_chat_agent.ChatResponse\"\x00\x12[\n\nChatStream\x12 .starland_chat_agent.ChatRequest\x1a\'.starland_chat_agent.ChatStreamResponse\"\x00\x30\x01\x62\x06proto3'
)




_CHATREQUEST = _descriptor.Descriptor(
  name='ChatRequest',
  full_name='starland_chat_agent.ChatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='starland_chat_agent.ChatRequest.message', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='character_id', full_name='starland_chat_agent.ChatRequest.character_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conversation_id', full_name='starland_chat_agent.ChatRequest.conversation_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='starland_chat_agent.ChatRequest.temperature', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=135,
)


_CHATRESPONSE = _descriptor.Descriptor(
  name='ChatResponse',
  full_name='starland_chat_agent.ChatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='starland_chat_agent.ChatResponse.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='starland_chat_agent.ChatResponse.err_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_text', full_name='starland_chat_agent.ChatResponse.response_text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=205,
)


_CHATSTREAMRESPONSE = _descriptor.Descriptor(
  name='ChatStreamResponse',
  full_name='starland_chat_agent.ChatStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='starland_chat_agent.ChatStreamResponse.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='starland_chat_agent.ChatStreamResponse.err_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chunk', full_name='starland_chat_agent.ChatStreamResponse.chunk', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=273,
)

DESCRIPTOR.message_types_by_name['ChatRequest'] = _CHATREQUEST
DESCRIPTOR.message_types_by_name['ChatResponse'] = _CHATRESPONSE
DESCRIPTOR.message_types_by_name['ChatStreamResponse'] = _CHATSTREAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatRequest = _reflection.GeneratedProtocolMessageType('ChatRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHATREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:starland_chat_agent.ChatRequest)
  })
_sym_db.RegisterMessage(ChatRequest)

ChatResponse = _reflection.GeneratedProtocolMessageType('ChatResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHATRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:starland_chat_agent.ChatResponse)
  })
_sym_db.RegisterMessage(ChatResponse)

ChatStreamResponse = _reflection.GeneratedProtocolMessageType('ChatStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHATSTREAMRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:starland_chat_agent.ChatStreamResponse)
  })
_sym_db.RegisterMessage(ChatStreamResponse)



_AGENT = _descriptor.ServiceDescriptor(
  name='Agent',
  full_name='starland_chat_agent.Agent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=276,
  serialized_end=455,
  methods=[
  _descriptor.MethodDescriptor(
    name='Chat',
    full_name='starland_chat_agent.Agent.Chat',
    index=0,
    containing_service=None,
    input_type=_CHATREQUEST,
    output_type=_CHATRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ChatStream',
    full_name='starland_chat_agent.Agent.ChatStream',
    index=1,
    containing_service=None,
    input_type=_CHATREQUEST,
    output_type=_CHATSTREAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGENT)

DESCRIPTOR.services_by_name['Agent'] = _AGENT

# @@protoc_insertion_point(module_scope)
